title: YELANDAOKONG
description: Github Page (Work)
show_downloads: false
###########################################################################################
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sass-converter
sass:
  sass_dir: assets/css
###########################################################################################
features:
  layout: false
include:
  - head-custom.html
  - giscus.html
